### ISSUE TITLE
Notworking (correctly) on Blender 2.77a

### ISSUE THREAD

**Issue by callimero** [zeffii/rawr#1]
Hi,

I tried your script in Blender 2.77 and at first it looked ok, but then after trying more objects, I found that it only works when the Object is in the Scene center... Did something changed in Blender or is this a known limitation?

Cheers,
Carsten

**Comment by zeffii** [comment]
Hi @callimero . I'm not sure which script you're using. But it's quite probably that it does rely on the object's origin being on (x=0, y=0, z=0).

**Comment by callimero** [comment]
I was using the one for selecting just the front faces. I cant fins it right now here :-/ I think you used it for a SVG renderer. Found it via blender.stackechange

**Comment by callimero** [comment]
Ah this one: https://gist.github.com/zeffii/5766177

**Comment by zeffii** [comment]
I don't think anything in Blender changed significant to this script. That it doesn't work for objects with their origin translated away from the center doesn't surprise me - I only used as a minor example, to give people an idea where to start.

**Comment by leftover** [comment]
if anyone cares 5 years later :)
Probably the issue is caused by this line:
`pnormal = obj.matrix_world * polygon.normal`
should be:
`pnormal = obj.matrix_world.to_quaternion() * polygon.normal`
(As well current version of mathutils uses operator @ instead of * )

**Comment by zeffii** [comment]
nope. time to move on :)
